
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: jiren
  
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: search_engine_development

test:
  <<: *default
  database: search_engine_test


production:
  <<: *default
  database: search_engine_production
  username: search_engine
  password: <%= ENV["SEARCH_ENGINE_DATABASE_PASSWORD"] %>
